const routes = [
  { path: '/', title: 'Executive Dashboard', nav: 'Home' },
  { path: '/platforms', title: 'Platform Ecosystem', nav: 'Platforms' },
  { path: '/platforms/evoucher', title: 'eVoucher Enterprise Platform', nav: 'eVoucher' },
  { path: '/services', title: 'Services', nav: 'Services' },
  { path: '/methodology', title: 'Methodology', nav: 'Methodology' },
  { path: '/architecture', title: 'Architecture Studio', nav: 'Architecture' },
  { path: '/architecture/gallery', title: 'Architecture Gallery', nav: 'Gallery' },
  { path: '/architecture/platform', title: 'Platform Architecture', nav: 'Platform Architecture' },
  { path: '/architecture/integration', title: 'Integration Architecture', nav: 'Integration' },
  { path: '/repository', title: 'Enterprise Repository', nav: 'Repository' },
  { path: '/repository/architecture', title: 'Repository | Architecture', nav: 'Repo Architecture' },
  { path: '/repository/apis', title: 'Repository | APIs', nav: 'Repo APIs' },
  { path: '/repository/data', title: 'Repository | Data', nav: 'Repo Data' },
  { path: '/repository/security', title: 'Repository | Security', nav: 'Repo Security' },
  { path: '/repository/infrastructure', title: 'Repository | Infrastructure', nav: 'Repo Infrastructure' },
  { path: '/repository/governance', title: 'Repository | Governance', nav: 'Repo Governance' },
  { path: '/case-studies', title: 'Case Studies', nav: 'Case Studies' },
  { path: '/case-studies/evoucher', title: 'Case Study | eVoucher Enterprise Platform', nav: 'eVoucher Case' },
  { path: '/contact', title: 'Contact', nav: 'Contact' },
];

const primaryNav = [
  ['Platforms', '/platforms'],
  ['Services', '/services'],
  ['Methodology', '/methodology'],
  ['Architecture', '/architecture'],
  ['Repository', '/repository'],
  ['Case Studies', '/case-studies'],
  ['Contact', '/contact'],
];

const signals = [
  ['Enterprise FinTech', 'Financial platform architecture'],
  ['Platform Engineering', 'Web, backend and operational systems'],
  ['Financial Operations', 'Billing, ledger, settlement, reconciliation'],
  ['Architecture', 'Business to application to data to infrastructure'],
  ['Operational Visibility', 'Dashboards, monitoring and BI'],
  ['Enterprise Documentation', 'Architecture and technical repository'],
];

const platformModules = [
  {
    id: 'consumer-marketplace',
    name: 'Consumer Marketplace',
    layer: 'Experience Layer',
    purpose: 'Customer-facing discovery, purchase, voucher and support experience.',
    problem: 'Customers need a clear path from product discovery to usable voucher value.',
    evidence: 'Consumer journey, voucher purchase flow and platform experience design.',
    href: '/platforms/evoucher',
    tier: 'experience',
  },
  {
    id: 'merchant-portal',
    name: 'Merchant Portal',
    layer: 'Operations Layer',
    purpose: 'Merchant onboarding, product setup, branch context and commercial visibility.',
    problem: 'Merchants need a controlled operating surface for participation in the platform.',
    evidence: 'Merchant operations, catalogue configuration and branch-aware platform logic.',
    href: '/platforms/evoucher',
    tier: 'operations',
  },
  {
    id: 'payment',
    name: 'Payment',
    layer: 'Financial Boundary',
    purpose: 'Controlled payment transaction creation and traceable reference propagation.',
    problem: 'A purchase must create evidence that can continue through voucher, billing and reconciliation.',
    evidence: 'Payment transaction reference, controlled provider boundary and lifecycle trace.',
    href: '/architecture/integration',
    tier: 'finance',
  },
  {
    id: 'voucher-engine',
    name: 'Voucher Engine',
    layer: 'Application Layer',
    purpose: 'Voucher creation, ownership, expiry and redemption readiness.',
    problem: 'Purchased value must become controlled, auditable voucher value.',
    evidence: 'Voucher lifecycle, customer voucher record and redemption preparation.',
    href: '/architecture/platform',
    tier: 'application',
  },
  {
    id: 'billing-engine',
    name: 'Billing Engine',
    layer: 'Financial Operations Layer',
    purpose: 'Financial event processing, merchant invoicing and lifecycle visibility.',
    problem: 'Finance teams need to see how a transaction moves from purchase to ledger, payout, invoice, settlement and reconciliation.',
    evidence: 'Billing Engine, billing events, voucher ledger, payout, invoice, settlement and BankServ queue visibility.',
    href: '/case-studies/evoucher',
    tier: 'finance',
  },
  {
    id: 'voucher-ledger',
    name: 'Voucher Ledger',
    layer: 'Financial Control Layer',
    purpose: 'Traceable movement of voucher value through controlled accounting-style entries.',
    problem: 'Value movement must remain explainable after the customer and merchant experience completes.',
    evidence: 'Ledger entries tied to transaction references and billing events.',
    href: '/repository/data',
    tier: 'finance',
  },
  {
    id: 'settlement',
    name: 'Settlement',
    layer: 'Financial Operations Layer',
    purpose: 'Settlement calculation and preparation for merchant-facing financial closure.',
    problem: 'Completed transactions need a path toward payable settlement evidence.',
    evidence: 'Settlement records, payout preparation and external banking boundary.',
    href: '/architecture/platform',
    tier: 'finance',
  },
  {
    id: 'merchant-payout',
    name: 'Merchant Payout',
    layer: 'Financial Operations Layer',
    purpose: 'Merchant payable calculation and payout evidence.',
    problem: 'Merchants need confidence that financial outcomes are controlled and auditable.',
    evidence: 'Merchant payout records and invoice linkage.',
    href: '/repository/data',
    tier: 'finance',
  },
  {
    id: 'infrastructure',
    name: 'Infrastructure',
    layer: 'Infrastructure Layer',
    purpose: 'Deployment, environment, operational readiness and platform health surface.',
    problem: 'A platform must be observable and deployable, not only coded.',
    evidence: 'Vercel deployment, GitHub Actions and infrastructure dashboard direction.',
    href: '/repository/infrastructure',
    tier: 'infrastructure',
  },
  {
    id: 'analytics',
    name: 'Analytics',
    layer: 'Business Intelligence Layer',
    purpose: 'Executive visibility, operating insight and decision support.',
    problem: 'Leaders need to understand platform behavior without reading raw system records.',
    evidence: 'Dashboard engineering, lifecycle reporting and BI-ready data thinking.',
    href: '/architecture/gallery',
    tier: 'data',
  },
  {
    id: 'mobile',
    name: 'Mobile',
    layer: 'Experience Layer',
    purpose: 'Mobile-first access for customers and operational users.',
    problem: 'Platform access must fit real user contexts beyond desktop administration.',
    evidence: 'Mobile application channel represented in the platform ecosystem.',
    href: '/platforms/evoucher',
    tier: 'experience',
  },
  {
    id: 'ussd',
    name: 'USSD',
    layer: 'Inclusive Access Layer',
    purpose: 'Low-bandwidth access channel for assisted and inclusive customer journeys.',
    problem: 'Fintech platforms must account for customers who cannot depend on rich web access.',
    evidence: 'USSD journey architecture and assisted access channel planning.',
    href: '/architecture/integration',
    tier: 'integration',
  },
  {
    id: 'enterprise-repository',
    name: 'Enterprise Repository',
    layer: 'Evidence Layer',
    purpose: 'Architecture, APIs, data, security, infrastructure and governance artefacts.',
    problem: 'Enterprise platforms need durable knowledge, not undocumented heroics.',
    evidence: 'Repository routes, artefact placeholders and documentation governance model.',
    href: '/repository',
    tier: 'evidence',
  },
];

const valueJourney = [
  ['Consumer discovers product', 'Consumer Marketplace', 'Offer and merchant context', 'Product, merchant and customer intent', 'A buyer understands available value.'],
  ['Consumer purchases', 'Payment', 'Transaction reference is created', 'Payment transaction and reference', 'The purchase becomes traceable.'],
  ['Payment is processed', 'Payment Boundary', 'Provider status controls the next step', 'Payment status and metadata', 'The platform knows whether value can be issued.'],
  ['Voucher is created', 'Voucher Engine', 'Value becomes a voucher liability', 'Voucher code and customer voucher record', 'The customer receives controlled voucher value.'],
  ['Billing event is recorded', 'Billing Engine', 'Commercial event becomes finance evidence', 'Billing event and transaction correlation', 'Finance can inspect the purchase lifecycle.'],
  ['Ledger records transaction', 'Voucher Ledger', 'Accounting-style value movement is captured', 'Ledger debit and credit entries', 'Value movement can be audited.'],
  ['Settlement is calculated', 'Settlement Engine', 'Merchant payable path is prepared', 'Settlement and payout calculation', 'The merchant financial outcome becomes visible.'],
  ['Merchant payout is prepared', 'Merchant Payout', 'Payable evidence links back to source transaction', 'Payout and invoice records', 'Finance can review payout readiness.'],
  ['Operations monitor platform', 'Infrastructure', 'Deployment and operations are part of the platform', 'Operational evidence and deployment state', 'The system can be supported.'],
  ['Business intelligence provides visibility', 'Analytics', 'Executives see behavior, not raw tables', 'Dashboard and reporting signals', 'Leadership can make decisions.'],
];

const architectureLayers = [
  ['Business', 'Clarifies the business model, operating goals and transformation case.', 'business'],
  ['Application', 'Defines platform modules, portals, engines, dashboards and user surfaces.', 'application'],
  ['Data', 'Transaction, voucher, customer, billing and settlement information must remain traceable across the platform.', 'data'],
  ['Integration', 'Connects systems using APIs, event contracts, callbacks and controlled boundaries.', 'integration'],
  ['Infrastructure', 'Positions hosting, environments, deployments, observability and resilience.', 'infrastructure'],
  ['Operations', 'Turns delivery into ongoing support, monitoring, improvement and governance.', 'operations'],
];

const gallery = [
  ['Platform Architecture', 'Application', 'How business capability becomes modules, services and control surfaces.', '/architecture/platform'],
  ['Financial Architecture', 'Financial Operations', 'Payment, voucher, billing, ledger, payout, settlement and reconciliation movement.', '/case-studies/evoucher'],
  ['Integration Architecture', 'Integration', 'System contracts, APIs, events, callbacks and platform interoperability.', '/architecture/integration'],
  ['Data Architecture', 'Data', 'Operational records, evidence, reporting models and BI-ready structure.', '/repository/data'],
  ['Infrastructure Architecture', 'Infrastructure', 'Deployment, environment, monitoring and platform operations.', '/repository/infrastructure'],
  ['Security Architecture', 'Security', 'Access control, audit, privacy and controlled administrative surfaces.', '/repository/security'],
  ['Operations Architecture', 'Operations', 'Support, monitoring, reconciliation and continuous platform improvement.', '/repository/governance'],
];

const services = [
  ['Fragmented Systems', 'Your business operates across disconnected systems.', 'Integrated enterprise platforms, APIs, data flows, financial workflows and operational dashboards.', 'A coherent platform direction that joins business activity together.'],
  ['Enterprise Architecture', 'Delivery starts before the operating model is understood.', 'Discovery, capability mapping, architecture decisions, data and integration design.', 'Clarity before development begins.'],
  ['Digital Platform Engineering', 'Teams need more than a website; they need an operating platform.', 'Web applications, backend services, APIs, automation and dashboards.', 'A platform that supports real workflows.'],
  ['Financial Systems', 'Billing, settlement and reconciliation are fragmented or opaque.', 'Traceable financial events, ledger thinking, payout flows and invoice visibility.', 'Greater financial control and operational confidence.'],
  ['Integration', 'Critical systems do not speak to each other reliably.', 'API contracts, events, callbacks and external system boundaries.', 'Cleaner data movement and fewer hidden handoffs.'],
  ['Business Automation', 'Manual processes slow teams down and hide risk.', 'Workflow automation, approvals, audit trails and operational control surfaces.', 'More consistent execution and better visibility.'],
  ['Dashboard Engineering', 'Leadership cannot see operational reality quickly enough.', 'Executive dashboards, operational views, BI structure and evidence-led reporting.', 'Decision-ready visibility across platform activity.'],
];

const methodology = [
  ['Discover', 'Understand the business context and operating problem.', 'Business analysis, stakeholder discovery, process mapping, capability mapping.', 'Business capability map and current-state assessment.'],
  ['Design', 'Shape the enterprise solution before delivery pressure takes over.', 'Architecture, user journeys, data, integration and security.', 'Architecture blueprint and delivery backlog.'],
  ['Build', 'Engineer the platform in controlled increments.', 'Platform engineering, APIs, applications and automation.', 'Working platform components with traceable technical decisions.'],
  ['Deliver', 'Move the platform into usable operating shape.', 'Deployment, testing, training and documentation.', 'Released platform with known controls and handover material.'],
  ['Operate', 'Keep the platform observable, improvable and evidence-led.', 'Monitoring, support, analytics and continuous improvement.', 'Operational intelligence and sustainable platform evolution.'],
];

const repoCategories = [
  ['Architecture', '/repository/architecture', 'Architecture principles, diagrams, decision records and platform views.', ['Platform architecture overview', 'Decision records in development', 'Architecture diagrams being prepared']],
  ['APIs', '/repository/apis', 'API catalogues, request/response contracts and integration notes.', ['API catalogue in development', 'Integration contracts being prepared', 'Webhook documentation placeholder']],
  ['Data', '/repository/data', 'Data models, event records, reporting structures and BI evidence.', ['Transaction lifecycle model', 'Voucher and billing data view', 'BI model in development']],
  ['Security', '/repository/security', 'Access control, auditability, privacy posture and governance evidence.', ['Access control overview', 'Audit trail model', 'Security notes being prepared']],
  ['Infrastructure', '/repository/infrastructure', 'Deployment topology, environments, operations and monitoring evidence.', ['Vercel deployment pipeline', 'Environment model in development', 'Monitoring view placeholder']],
  ['Governance', '/repository/governance', 'Decision logs, controls, documentation standards and delivery governance.', ['Documentation standards', 'Review controls in development', 'Operational governance notes']],
];

const evidence = [
  ['Live eVoucher Platform', 'Production platform surface', 'https://www.evoucher.co.za'],
  ['Billing Engine', 'Financial operations and lifecycle visibility', '/case-studies/evoucher'],
  ['Voucher Ledger', 'Transaction tracking and financial control evidence', '/repository/data'],
  ['Infrastructure Dashboard', 'Platform operations design direction', '/repository/infrastructure'],
  ['GitHub Repository', 'Portfolio deployment and CI evidence', 'https://github.com/shelod-eng/mpetalebo-portfolio'],
  ['Architecture Diagrams', 'Architecture gallery and repository framework', '/architecture/gallery'],
  ['Deployment Pipeline', 'GitHub Actions and Vercel production deployment', 'https://github.com/shelod-eng/mpetalebo-portfolio/actions'],
];

const thinking = [
  'Technology should not simply automate a process. It should improve how the business operates.',
  'Architecture should create clarity before development begins.',
  'Financial systems require traceability, control and reconciliation.',
  'Operational visibility is part of platform design.',
  'Documentation is part of engineering.',
];

module.exports = {
  routes,
  primaryNav,
  signals,
  platformModules,
  valueJourney,
  architectureLayers,
  gallery,
  services,
  methodology,
  repoCategories,
  evidence,
  thinking,
};
